/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelo
 */
public class frmSimularPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form frmSimularPrestamo
     */
    public frmSimularPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idclienteField = new javax.swing.JTextField();
        dniField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        edadField = new javax.swing.JTextField();
        mesesAntiguedadField = new javax.swing.JTextField();
        deudasVigentesField = new javax.swing.JTextField();
        idclienteLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        edadLabel = new javax.swing.JLabel();
        mesesAntiguedadLabel = new javax.swing.JLabel();
        deudasVigentesLabel = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnGenerarPrestamo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dniField.setEnabled(false);

        nombreField.setEnabled(false);

        edadField.setEnabled(false);

        mesesAntiguedadField.setEnabled(false);

        deudasVigentesField.setEnabled(false);

        idclienteLabel.setText("Idcliente:");

        dniLabel.setText("Dni:");

        nombreLabel.setText("Nombre:");

        edadLabel.setText("Edad:");

        mesesAntiguedadLabel.setText("Meses Antiguedad:");

        deudasVigentesLabel.setText("Deudas Vigentes:");

        btnBuscar.setText("Buscar");
        btnBuscar.setName(""); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGenerarPrestamo.setText("Generar Prestamo");
        btnGenerarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idclienteLabel)
                            .addComponent(dniLabel)
                            .addComponent(nombreLabel)
                            .addComponent(edadLabel)
                            .addComponent(mesesAntiguedadLabel)
                            .addComponent(deudasVigentesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idclienteField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(dniField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(nombreField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(edadField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(mesesAntiguedadField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(deudasVigentesField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarPrestamo)
                        .addGap(58, 58, 58)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idclienteLabel)
                    .addComponent(idclienteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadLabel)
                    .addComponent(edadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesesAntiguedadLabel)
                    .addComponent(mesesAntiguedadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deudasVigentesLabel)
                    .addComponent(deudasVigentesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnGenerarPrestamo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        cargarDatos(idclienteField.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPrestamoActionPerformed
        // TODO add your handling code here:
        int tipoCliente = 1;
        
        
        
        switch(tipoCliente){
            case 1:
                new frmSimulacionTipo1().setVisible(true);
                break;
            case 2:
                new frmSimulacionTipo2().setVisible(true);
                break;
            case 3:
                new frmSimulacionTipo3().setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Cliente no apto para prestamo");
        }
    }//GEN-LAST:event_btnGenerarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSimularPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSimularPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSimularPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSimularPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSimularPrestamo().setVisible(true);
            }
        });
    }
    
    private void cargarDatos(String id){
        switch(id){
            case "001":
                llenarFields("72630638","Angelo Licetti","20", "30", "N");
                break;
            case "002":
                llenarFields("78945612","Angelo Licetti","20", "4", "N");
                break;
            case "003":
                llenarFields("6987412","Henry Arias","20", "30", "S");
                break;
            case "004":
                llenarFields("84467812","Juan Perez","17", "2", "S");
                break;
            default:
                System.out.println("No existe");
        }
    }
    
    private void llenarFields(String dni, String nombre, String edad, String mesesAntiguedad, String deudasVigentes){
        dniField.setText(dni);
        nombreField.setText(nombre);
        edadField.setText(edad);
        mesesAntiguedadField.setText(mesesAntiguedad);
        deudasVigentesField.setText(deudasVigentes);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerarPrestamo;
    private javax.swing.JTextField deudasVigentesField;
    private javax.swing.JLabel deudasVigentesLabel;
    private javax.swing.JTextField dniField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField edadField;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JTextField idclienteField;
    private javax.swing.JLabel idclienteLabel;
    private javax.swing.JTextField mesesAntiguedadField;
    private javax.swing.JLabel mesesAntiguedadLabel;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables
}
